# Application
spring.application.name=security-service
server.port=8084

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# User
# JWT
jwt.secret=Jcau6mPiMUpCK3NflMzbvcgr0oVkILNhg7sb29Kh0yP
jwt.expiration=86400000

logstash.host=${LOGSTASH_HOST:localhost}
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=${spring.application.name}
